import Layout from "./components/Layout";
import "./globals.css";
export const metadata = {
  title: "Automarket",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang='en' data-theme='light'>
      <body suppressHydrationWarning={true}>
        <Layout>{children}</Layout>
      </body>
    </html>
  );
}
